library(ggtree)
library(treeio)
tree<-read.nhx("/Users/bguinet/Downloads/FullTree2") # The tree generated by the ete3 Python package 



tree@data$status[tree@data$status==1]<-"endo"
tree@data$status[tree@data$status==2]<-"exo"
tree@data$status[tree@data$status==3]<-"exo"

#plot the circulat tree 
p<- ggtree(tree, layout='circular',size=0.2)
p1<- groupClade(p, c(2000,1823,1683),group_name='subtree')+aes(color=subtree)

#Color vector
color_vector=c("1"="#5c6b73","2"="#9db4c0","3"="#81c3d7","endo"="#61d04f","exo"="#00335c")

#Plot the status along the phylogeny
p1 %<+% tree@data +
  geom_tippoint(size=4, shape="I",aes(subset= status>0,colour=factor(status)))+
  scale_colour_manual(values = color_vector)

